"""add merchant aliases

Revision ID: 558b529a85c3
Revises: f3f492712968
Create Date: 2026-07-24 21:26:47.234817
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "558b529a85c3"
down_revision: str | Sequence[str] | None = "f3f492712968"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pattern"),
    )
    with op.batch_alter_table("merchant_aliases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_merchant_aliases_merchant_id"), ["merchant_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("merchant_aliases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchant_aliases_merchant_id"))

    op.drop_table("merchant_aliases")
    # ### end Alembic commands ###
