"""create initial expense schema

Revision ID: 64949b9ed7bb
Revises:
Create Date: 2026-07-24 20:05:19.783407
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "64949b9ed7bb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("parent_category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_parent_category_id"), ["parent_category_id"], unique=False
        )

    op.create_table(
        "import_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("total_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "categorisation_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_pattern", sa.String(length=500), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("categorisation_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categorisation_rules_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_categorisation_rules_enabled"), ["enabled"], unique=False
        )

    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("import_batch_id", sa.Integer(), nullable=True),
        sa.Column("merchant_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("matched_rule_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "imported",
                "normalised",
                "merchant_identified",
                "categorised",
                "needs_review",
                name="transaction_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="imported",
            nullable=False,
        ),
        sa.Column("categorisation_source", sa.String(length=50), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)",
            name="ck_expenses_confidence_score_range",
        ),
        sa.CheckConstraint("length(currency) = 3", name="ck_expenses_currency_length"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["import_batch_id"], ["import_batches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["matched_rule_id"], ["categorisation_rules.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_expenses_category_id"), ["category_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_expenses_import_batch_id"), ["import_batch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_expenses_matched_rule_id"), ["matched_rule_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_expenses_merchant_id"), ["merchant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_expenses_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_expenses_transaction_date"), ["transaction_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expenses_transaction_date"))
        batch_op.drop_index(batch_op.f("ix_expenses_status"))
        batch_op.drop_index(batch_op.f("ix_expenses_merchant_id"))
        batch_op.drop_index(batch_op.f("ix_expenses_matched_rule_id"))
        batch_op.drop_index(batch_op.f("ix_expenses_import_batch_id"))
        batch_op.drop_index(batch_op.f("ix_expenses_category_id"))

    op.drop_table("expenses")
    with op.batch_alter_table("categorisation_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categorisation_rules_enabled"))
        batch_op.drop_index(batch_op.f("ix_categorisation_rules_category_id"))

    op.drop_table("categorisation_rules")
    op.drop_table("merchants")
    op.drop_table("import_batches")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_parent_category_id"))

    op.drop_table("categories")
    # ### end Alembic commands ###
