"""store raw imported transactions

Revision ID: d4d85d7fe82d
Revises: 64949b9ed7bb
Create Date: 2026-07-24 20:32:28.287074
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d4d85d7fe82d"
down_revision: str | Sequence[str] | None = "64949b9ed7bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("import_batch_id", sa.Integer(), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["import_batch_id"], ["import_batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "import_batch_id", "source_row_number", name="uq_raw_transactions_batch_row"
        ),
    )
    with op.batch_alter_table("raw_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_transactions_import_batch_id"), ["import_batch_id"], unique=False
        )

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("raw_transaction_id", sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(
            "uq_expenses_raw_transaction_id",
            ["raw_transaction_id"],
        )
        batch_op.create_foreign_key(
            "fk_expenses_raw_transaction_id",
            "raw_transactions",
            ["raw_transaction_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_constraint("fk_expenses_raw_transaction_id", type_="foreignkey")
        batch_op.drop_constraint("uq_expenses_raw_transaction_id", type_="unique")
        batch_op.drop_column("raw_transaction_id")

    with op.batch_alter_table("raw_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_transactions_import_batch_id"))

    op.drop_table("raw_transactions")
    # ### end Alembic commands ###
