"""track normalisation workflow

Revision ID: f3f492712968
Revises: d4d85d7fe82d
Create Date: 2026-07-24 20:45:29.308390
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f3f492712968"
down_revision: str | Sequence[str] | None = "d4d85d7fe82d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("normalised_description", sa.String(length=500), nullable=True)
        )

    op.execute(sa.text("UPDATE expenses SET normalised_description = upper(trim(description))"))

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.alter_column(
            "normalised_description",
            existing_type=sa.String(length=500),
            nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_expenses_normalised_description"),
            ["normalised_description"],
            unique=False,
        )

    with op.batch_alter_table("raw_transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("normalisation_error", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_transactions", schema=None) as batch_op:
        batch_op.drop_column("normalisation_error")

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expenses_normalised_description"))
        batch_op.drop_column("normalised_description")

    # ### end Alembic commands ###
